name: staticcheck

on:
  pull_request:
    branches: [main, prod]

jobs:
  test:
    name: staticcheck
    runs-on: ubuntu-latest
    env:
      GOPROXY: "https://proxy.golang.org,direct"

    steps:
      - name: Set up Go 1.22.5
        uses: actions/setup-go@v2
        with:
          go-version: '1.22.5'
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: install staticcheck
        run: |
          cd /tmp && go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: make staticcheck
        env:
          GOFLAGS: -mod=vendor
        run: |
          make staticcheck
