name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      GOPROXY: "https://proxy.golang.org,direct"

    steps:
      - name: Set up Go 1.22.2
        uses: actions/setup-go@v2
        with:
          go-version: '1.22.2'
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: install govulncheck
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          go install golang.org/x/vuln/cmd/govulncheck@latest

      - name: test
        env:
          GOFLAGS: -mod=vendor
        run: |
          go test ./...
